apiVersion: v1
kind: Service
metadata:
  name: urlshortener
spec:
  type: NodePort
  selector:
    {{- include "urlshortener.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort | default 38080 }}
